### ISSUE TITLE
Handler not found error from BL

### ISSUE THREAD

**Issue by brentonp07** [bacanu/blwrap#1]
I am trying to call Get Item and Get Item Image, however I am receiving a Handler Not Found! error from Bricklink. I am not seeing this error on previous revisions of our API calls, and the other methods are working. Let me know if you have time to look into this, or I might be able to take a look at it.

Thanks!

**Comment by bacanu** [comment]
I'll look into it today and hopefully give you a response by tomorrow.

**Comment by brentonp07** [comment]
Thank you sir!

**Comment by bacanu** [comment]
Most likely your problem is that you are using an endpoint  that starts with a `/`  
The endpoint should not have a `/` in front of it.

Not OK: `/items/part/1234` -->  `$bl->execute('get', '/items/part/1234');`  

OK: `items/part/1234` -->  `$bl->execute('get', 'items/part/1234');`

**Comment by brentonp07** [comment]
Awesome, sorry about that. A nice note and kudos to you, your wrapper is running at 16 queries per second whereas our other wrapper was running at 4 queries per second
